In [1]:
x=5

In [2]:
x

5

In [3]:
a = [1,2,3,4]

In [4]:
a

[1, 2, 3, 4]

In [5]:
len(a)

4

In [6]:
a[0]

1

In [7]:
a[0:2]

[1, 2]

In [9]:
a[0:len(a)]

[1, 2, 3, 4]

In [12]:
for elem in a:
    x=elem
    y=elem+1
    print("x is",x,"y is",y)

x is 1 y is 2
x is 2 y is 3
x is 3 y is 4
x is 4 y is 5


In [15]:
for elem in range(1,5):
    print(elem)

1
2
3
4


In [16]:
lst = [x*x for x in range(1,11)]

In [17]:
lst

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [18]:
lst = [a[i+1] for i in range(3)]

In [19]:
lst

[2, 3, 4]

In [20]:
x = [1,3,5]
y = [4,6,7]

In [22]:
sum([x[i]*y[i] for i in range(len(x))])

57

In [23]:
def dot_product(x,y):
  return sum([x[i]*y[i] for i in range(len(x))])

In [24]:
dot_product([1,2],[3,5])

13

In [25]:
import numpy

In [27]:
help(numpy.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [30]:
import numpy as np

In [31]:
a = np.array([1,2,3])

In [32]:
a

array([1, 2, 3])

In [33]:
b = np.array([4,5,6])

In [34]:
a.dot(b)

32

In [35]:
np.dot(a,b)

32

In [40]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [41]:
mnist.train.images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [42]:
mnist.train.images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [43]:
len(mnist.train.images[0])

784

In [44]:
mnist.train.images.shape

(55000, 784)

In [48]:
mnist.train.labels[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

In [49]:
np.dot(mnist.train.images[0],mnist.train.images[1])

32.35136

In [57]:
a = np.array([1,2,3,4])

In [58]:
np.linalg.norm(a)

5.477225575051661

In [59]:
a / np.linalg.norm(a)

array([0.18257419, 0.36514837, 0.54772256, 0.73029674])

In [60]:
img_norms = np.linalg.norm(mnist.train.images,axis=0)

In [62]:
img_norms.shape

(784,)

In [63]:
img_norms = np.linalg.norm(mnist.train.images,axis=1)

In [64]:
img_norms.shape

(55000,)

In [66]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [67]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
m / np.array([1,2,3])

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ],
       [7. , 4. , 3. ]])

In [69]:
m / np.array([[1],[2],[3]])

array([[1.        , 2.        , 3.        ],
       [2.        , 2.5       , 3.        ],
       [2.33333333, 2.66666667, 3.        ]])

In [71]:
m / np.array([1,2,3]).reshape([1,3])

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ],
       [7. , 4. , 3. ]])

In [73]:
normalized_images = mnist.train.images / img_norms.reshape([55000,1])

In [74]:
normalized_images.shape

(55000, 784)

In [75]:
%matplotlib inline
import matplotlib.pyplot as plt
def show(num):
    plt.axis('off')
    plt.imshow()
    plt.imshow(num.reshape(-1,28),cmap='gray')

In [76]:
mnist.train.images.dot(
    normalized_images[-1].reshape([784,1]))

array([[3.4697518],
       [4.7063866],
       [2.2834904],
       ...,
       [3.397404 ],
       [2.6706285],
       [7.9767547]], dtype=float32)

In [77]:
# TensorFlow
import tensorflow as tf

In [78]:
g = tf.get_default_graph()

In [80]:
#The operations of this graph are empty.
g.get_operations()

[]

In [106]:
tf.reset_default_graph()
g = tf.get_default_graph()
x = tf.placeholder(tf.float32,[None,784])
y = tf.placeholder(tf.float32,[None,10])
w = tf.Variable(tf.truncated_normal([784,10], stddev=0.1))
b = tf.Variable(tf.truncated_normal([10],stddev=0.1))
scores = tf.add(tf.matmul(x,w),b)


loss = tf.nn.softmax_cross_entropy_with_logits(logits=scores,labels=y)
avg_loss = tf.reduce_mean(loss)
train_step = tf.train.GradientDescentOptimizer(0.01).minimize(loss)
initialize_all = tf.global_variables_initializer()

In [107]:
sess = tf.Session()

In [92]:
g.get_operations()

[<tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'Placeholder_1' type=Placeholder>,
 <tf.Operation 'truncated_normal/shape' type=Const>,
 <tf.Operation 'truncated_normal/mean' type=Const>,
 <tf.Operation 'truncated_normal/stddev' type=Const>,
 <tf.Operation 'truncated_normal/TruncatedNormal' type=TruncatedNormal>,
 <tf.Operation 'truncated_normal/mul' type=Mul>,
 <tf.Operation 'truncated_normal' type=Add>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'truncated_normal_1/shape' type=Const>,
 <tf.Operation 'truncated_normal_1/mean' type=Const>,
 <tf.Operation 'truncated_normal_1/stddev' type=Const>,
 <tf.Operation 'truncated_normal_1/TruncatedNormal' type=TruncatedNormal>,
 <tf.Operation 'truncated_normal_1/mul' type=Mul>,
 <tf.Operation 'truncated_normal_1' type=Add>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.

In [108]:
sess.run(initialize_all)

In [109]:
sess.run(b)

array([-0.10638391,  0.01339845,  0.01217899,  0.068494  ,  0.00264609,
        0.04329933, -0.08945136, -0.14974956, -0.03542972, -0.04694886],
      dtype=float32)

In [111]:
sess.run(avg_loss,feed_dict={x: mnist.train.images[0:100],
                        y: mnist.train.labels[0:100]})

2.5460505

In [120]:
#Do 550 step of gradient descent
for i in range(550):
    start = i*100
    end = (i+1)*100
    sess.run(train_step,feed_dict={x: mnist.train.images[start:end],
                        y: mnist.train.labels[start:end]})

In [121]:
sess.run(avg_loss,feed_dict={x: mnist.train.images[0:100],
                        y: mnist.train.labels[0:100]})

0.31373993

In [122]:
sess.run(avg_loss,feed_dict={x: mnist.test.images,
                        y: mnist.test.labels})

0.3309998

In [123]:
computed_scores = sess.run(scores,feed_dict={x: mnist.test.images,
                        y: mnist.test.labels})

In [125]:
computed_scores.shape

(10000, 10)

In [126]:
np.argmax(computed_scores,axis=1)

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [128]:
np.argmax(mnist.test.labels,axis=1)

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)